# -*- coding: utf-8 -*-
"""eng_to_hi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rkWP8MpRp6p8e3h4AmG-jqDsCvS3_w5y
"""

from huggingface_hub import InferenceClient

# Get HF Key
from google.colab import userdata
hugging_face_key = userdata.get('HF_TOKEN')

model_id = "Helsinki-NLP/opus-mt-en-hi"
client = InferenceClient(model=model_id, token= hugging_face_key)

hindi_translation = client.translation("Did you play cricket yesterday?")

print(hindi_translation)

